watch:
  directories:
    - src
    - tests/Controller
  fileMask: '*.php'
notifications:
  passingTests: true
  failingTests: true
  errorTests: true
phpunit:
  binaryPath: vendor/bin/simple-phpunit
  arguments: '--stop-on-error --stop-on-failure'
  timeout: 180
# hideManual: false