language: php
php:
  # - "7.2"
  - "7.3"

script:
  - composer install
  - npm install
  - npm run build
  - php bin/console doctrine:database:create --env=test   
  - php bin/console doctrine:schema:update --env=test --force   
  - php bin/phpunit tests/Entity
  - php bin/phpunit tests/Repository
  - php bin/phpunit tests/Controller
  #- vendor/bin/phpunit # vendor/bin/phpunit/home/travis/.travis/functions: line 109: vendor/bin/phpunit: No such file or directory


# jobs:
#   include:
#     - language: node_js
#       node_js: 
#         - "6.12"
#       before_install: npm install -g grunt-cli
#       install: npm install
#       # before_script: grunt build
#       script:
#         - npm run build
#     - language: php
#       php: "7.3"
#       script:
#         - php bin/phpunit tests/controller

