language: php
php:
  # - "7.2"
  - "7.3"


script:
  - composer install
  # - npm run build
  # - vendor/bin/phpunit
  # - php bin/phpunit
  # - php ./vendor/bin/phpunit # Could not open input file: ./vendor/bin/phpunit
  - vendor/bin/simple-phpunit