language: php
php:
  # - "7.2"
  - "7.3"

script:
  - composer install
  - yarn install
  # - npm cache clean --force
  - npm run build
  - php bin/console doctrine:database:create --env=test   
  - php bin/console doctrine:schema:update --env=test --force   
  - php bin/phpunit tests/Entity
  - php bin/phpunit tests/Repository
  - php bin/phpunit tests/Controller