language: php
php:
  # - "7.2"
  - "7.3"


script:
  - composer install
  - php bin/phpunit
  #- vendor/bin/phpunit # vendor/bin/phpunit/home/travis/.travis/functions: line 109: vendor/bin/phpunit: No such file or directory
  # - npm run build